### PR TITLE
PR for issue #72

### PR DESCRIPTION
**Pull request by OleRoel**
Renamed `find`to `findRecord` and added `find`method, which forward calls to `findRecord`to keep backward compatibility.

### CODE REVIEW

**Comment by rsutphin** [comment]
@OleRoel, thanks for taking this on.

It looks like you've got some extra commits in your PR branch, like there were in #67. We'd want to avoid this to keep the history in the main repo clear and easy to understand after the PR is merged.

To avoid getting into this situation, you want to do two things:

* Before you make your feature branch, make sure your local master & and your fork's master branch match the current master here, in upstream.
* Don't ever merge into the feature branch. If you need to bring in upstream changes before you submit your PR, use rebase instead.

[This is a detailed overview of how you can and why you would do this](https://github.com/edx/edx-platform/wiki/How-to-Rebase-a-Pull-Request). Here's a summary for your current situation, but be careful because some of these actions are destructive if you do them wrong. These instructions assume that your fork is checked out and its remote is called `origin` (if you `git clone`d your fork, this will be the case.)

* Make a feature branch from your current master (since it has the changes you want to submit on it).

```
git branch 72-deprecated_find
```

* Retrieve the current upstream.

```
git remote add upstream git@github.com:nolanlawson/ember-pouch.git
git fetch --all
```

* Reset your local master to match upstream (this is a destructive step).

```bash
# ensure you are on master
git checkout master
git reset --hard upstream/master
```

* Update your remote master to match your new local, which matches upstream (this is also destructive). This is optional, but it will probably reduce confusion down the line.

```
git push --force origin master
```

* Rebase your feature branch over the new local master

```
git checkout 72-deprecated_find
git rebase master
```

There may be conflicts at this point. Follow the rebase prompts to resolve them. Once you are sure that the rebase was successful and your changes are present in the feature branch, continue.

* Close this PR, since it points at your master branch.
* Push the new feature branch to your fork

```
# Make sure you are on the feature branch
git checkout 72-deprecated_find
git push -u origin 72-deprecated_find
```

* Make a new PR based on the new feature branch.

**Comment by OleRoel** [comment]
@rsutphin Thank you for your detailed instructions, they are really appreciated. I am having a hard time to figure out how to use rebase and was thinking (hoping) to do it right this time, obvisouly I didn't get it again. The stupid thing is, that I am trying things out in public. So, please accept my excuse again, I don't want to create extra work here.

**Comment by OleRoel** [comment]
@rsutphin ...and I am now a bit fearful to push the hard reset master to my Git-repo, because I don't know what happens to the PR then. Should I execute another experiment in public and everyone promises to close their eyes while I am doing it? Or do you like to create a clean PR with the necessary changes and I will do my rebase afterwards? I don't mind doing a stunt while no one is watching.

**Comment by rsutphin** [comment]
I think the worst thing that would happen is that the PR would get automatically closed (because it has no changes in in any more). But I don't think anything terrible/unrecoverable would happen. I think it will be an interesting experiment and no one will hold anything against you regardless.

But if you really don't want to do it, you can always skip the step about force pushing your new local master. You can continue with the rest of the steps without doing that one.

**Comment by nolanlawson** [comment]
Thanks a lot; rebasing is definitely the preferred method since the Git repo doesn't end up looking like a subway map! :)

For the record @rsutphin, if there are no merge conflicts, I will often just manually rebase and squash the commits myself, and then change the author name to preserve original authorship. I find the whole rebasing thing to be a really difficult and error-prone thing, especially for newcomers. :P

**Pull request closed without merging**
