### PR TITLE
(#55) - minor fixups to ember-cli refactor

### PR DESCRIPTION
**Pull request by nolanlawson**

### CODE REVIEW

**Comment by nolanlawson** [comment]
@fsmanuel Actually, scratch what I said about `.npmignore` and `dist`. It appears that the ember-cli changes are actually breaking changes, since people who were `bower install`ing and using the files from `dist` apparently cannot use those same files anymore? What I'm seeing in `dist` seems to be the test assets, not the build assets like we used to have.

So to clarify: do I need to publish a 2.0.0 when I push your changes out?

**Comment by fsmanuel** [comment]
@nolanlawson i guess it should be 2.0.0. It should't be hard to provide a dist but i guess there is no need because ember-cli is the default way to get ember.

**Comment by nolanlawson** [comment]
Yup, that's what I thought. Let's publish this as 2.0.0 then.

**Comment by broerse** [comment]
Tested Dutch Serializer fix and it works with the addon

```
import { Serializer } from 'ember-pouch';

export default Serializer.extend({
  typeForRoot: function(root) {
    if (/ties$/i.test(root)) {
      return root.substr(0, root.length - 1);
    }
    return this._super(root);
  }
});
```

**Comment by fsmanuel** [comment]
@broerse what is it for? should we include it in the serializer?

**Comment by broerse** [comment]
No don't include it. It is just something we use in the Netherlands to go from a Dutch words like 'loca**ties**' to 'loca**tie**'. and learn Ember Dutch ;-) I was just testing if the new addin worked with this and it is working fine.

**Comment by nolanlawson** [comment]
I don't see much reason to wait to publish this; let's get it out there and test it. :) Gonna publish 2.0.0 tonight.

**Comment by nolanlawson** [comment]
Well, 2.0.0 is published now, and I can definitely install it using `ember install ember-pouch`.

However, I think we're definitely going to need some kind of TodoMVC-style guide (maybe in the readme, maybe in the wiki) that's actually up-to-date with the latest Ember changes. I've been trying to use the new Ember CLI workflow, and I find myself completely overwhelmed by the documentation.

**Comment by fsmanuel** [comment]
@nolanlawson some basic information about how ember-pouch works would be nice to. It took me some time to figure out how to work with ember-pouch:
- documents should have the data attribute or you have to use the transform plugin
- it's not possible to use your own ids at least i don't know how

What are the main problems with the ember-cli workflow? we could add a blueprint to add a basic pouch adapter...

**Comment by nolanlawson** [comment]
@fsmanuel I just mean for somebody who's new to Ember, it's not perfectly clear how to start out. E.g. it seems there's no `app/adapters/application.js` anymore, so how do you add a new adapter? Also I got an error when I tried to serve up the data from a route, so I couldn't figure out how to tie my model to my route.

Keep in mind that I have been not paying attention to Ember-land for the past 6 months or so, so it has changed so far beyond recognition that I'm basically a beginner again. :)

**Comment by srsgores** [comment]
@nolanlawson, just do ``ember g adapter application``.

**Comment by fsmanuel** [comment]
We should run a generator ourself that creates the application adapter if needed.

**Comment by srsgores** [comment]
I think this ``readme`` needs some work.  I would like to include some information on integrating with third-party providers like cloudant and iriscouch (like the original readme).  I think it all can be re-worded.

I'd be happy to make a PR.  @nolanlawson, what are your thoughts?

**Comment by nolanlawson** [comment]
@srsgores I'm happy with mentioning Cloudant and IrisCouch, although I don't think we should make a lengthy tutorial about how to use them. That info can be handled in the PouchDB wiki or on the PouchDB website itself.

That being said, we do need something in the README to help people get started. @fsmanuel either running our own generator or providing info in the README about how to do so are fine in my opinion; whatever is more common in the landscape of Ember adapters. :)

**Pull request merged**
