### PR TITLE
update ember-getowner-polyfill to remove deprecation warnings

### PR DESCRIPTION
**Pull request by akatov**
this is less radical than #173

### CODE REVIEW

**Comment by broerse** [comment]
@ntodd What do you think about this PR? Go with this one?

**Comment by fsmanuel** [comment]
@akatov 👍 
@broerse That is the correct way to remove the deprecation.

**Comment by ntodd** [comment]
@broerse Yeah, this way is correct.

**Comment by broerse** [comment]
@akatov @ntodd Thanks!

**Comment by colinf** [comment]
@broerse It would be great if you could publish to NPM with this change as I am getting an error "Could not find module `ember-getowner-polyfill` imported from `ember-pouch/adapters/pouch`" with the current NPM version and this fixes it. It might save other new users like me some headaches! Thanks.

**Comment by broerse** [comment]
@colinf @rwanyoike Sorry... v2.4.5 published now.

**Pull request merged**
