### PR TITLE
(#45) - fixes for EmberData pre-beta.15

### PR DESCRIPTION
**Pull request by nolanlawson**
This is my amended version of #46. It should support both EmberData beta.14 and beta.15.

### CODE REVIEW

**Comment by nolanlawson** [comment]
Could someone test this out and let me know if it works?

**Comment by nolanlawson** [comment]
Fixed the dist files.

**Comment by OleRoel** [comment]
The code changes are working for me with EmberData beta.14 and beta.15. But I haven't done the full git fetch/checkout, npm build cycle (actually, I need to figure out how to do this with a PR).

**Comment by nolanlawson** [comment]
I also have another confirmation from someone in the #pouchdb IRC channel. Gonna consider this fixed, thanks for the help! :)

**Pull request merged**
