### PR TITLE
remove deprecation warnings for 1.13

### LINKED ISSUE #78: Deprecation warnings coming from the change watcher with ED 1.13
Reported by @OleRoel in #72:

> * Using store.getById() has been deprecated. Use store.peekRecord to get a record by a given type and ID without triggering a fetch
> * DS.Model#isDirty has been deprecated please use hasDirtyAttributes instead
> * You tried to look up 'store:main', but this has been deprecated in favor of 'service:store'

I think these are all coming from the change watcher.

### PR DESCRIPTION
**Pull request by fivetanley**
fixes #78

This change will be incompatible with the betas of Ember Data, just fyi. Users will have to upgrade Ember Data as well.

### CODE REVIEW

**Comment by rsutphin** [comment]
@fivetanley, thanks for your attention to this. We are still trying to maintain backwards compatibility with the betas for the moment. Dropping backwards compatibility will require a major version bump.

I've tried eliminating the 1.13 deprecation warnings while preserving backwards compatibility. I was able to do it for all of them except for the `isDirty` check. Do know of a technique for that one?

**Comment by rsutphin** [comment]
… thinking about it a little more, the event we were waiting for to drop backwards compatibility was, IIRC, ember-data releasing 1.0. Since that's happened now (and then some), maybe it's time for that major version bump. Anyone else have an opinion?

**Comment by nolanlawson** [comment]
I'm not sure what percentage of Ember users have upgraded to 1.0, but I do see the value in getting rid of old cruft to deal with <1.0 versions. Agree with @rsutphin that it would be a breaking change, though.

**Comment by broerse** [comment]
Perhaps we can use [ember-cli-version-checker](https://github.com/rwjblue/ember-cli-version-checker) to fix this?

**Comment by rsutphin** [comment]
@broerse, we could do that, but we'd basically be maintaining two separate versions of the adapter then, just packaged together. Seems like if that's desirable we could just continue to maintain the 2.x line along with a new ED 1.13+-only 3.x line.

My guess is that there is not sufficient interest to maintain both lines, regardless of how they are packaged.

Does anyone have any objections to dropping compatibility with the ED betas?

**Comment by broerse** [comment]
I am for dropping compatibility with the ED betas. But I think we must give an error like this:

https://github.com/mharris717/ember-cli-pagination/commit/6781cdef37ceb75ff328ea4f92d26b0d05abd35a

**Comment by mattmarcum** [comment]
:+1: on dropping support for ED betas.

**Comment by openhouse** [comment]
:+1: I needed this branch for Ember 2.2.0 Ember Data 2.2.1. Woo hoo! Now it's working!

**Comment by rsutphin** [comment]
I've posted a PR (#95) which incorporates this one and officially drops compatibility with ember & ember-data earlier than 1.13.

**Pull request merged**
