### PR TITLE
Add return to addBowerPackagesToProject

### PR DESCRIPTION
**Pull request by broerse**

### CODE REVIEW

**Comment by nolanlawson** [comment]
Can you please provide more detail about this? I can't seem to find any info about this "blueprints" thing or what it's supposed to do.

**Comment by broerse** [comment]
Yes. addBowerPackagesToProject returns a promise. If you don't add the return the 2 bower modules are not installed.

**Comment by nolanlawson** [comment]
I trust ya, let's do it. :)

**Comment by nolanlawson** [comment]
BTW any thoughts on #58 and #59? Are we ready to go for a 2.0.0 release with ember-cli support?

**Comment by broerse** [comment]
Just updated to Ember Pouch ember-cli addon https://github.com/broerse/ember-cli-blog Will check #58 and #59 now.

**Comment by broerse** [comment]
I see no problem to do it now but...
Ember.js 2.0, Ember CLI 1.0, Ember Data 1.0, ListView 1.0, Liquid Fire 1.0 betas: all shipping on June 12
Perhaps add Ember Pouch to the the list and release 12 june?

**Comment by broerse** [comment]
#55 and https://github.com/nolanlawson/ember-pouch/blob/master/blueprints/ember-pouch/index.js need to be aligned before 2.0.0

**Comment by broerse** [comment]
For the 2.0.0 docs `ember install:addon ember-pouch` is now `ember install ember-pouch`

**Comment by fsmanuel** [comment]
@broerse good catch!

**Pull request merged**
