### PR TITLE
Check the rev to avoid unnecessary reloads in change watcher

### PR DESCRIPTION
**Pull request by broerse**
PR for https://github.com/nolanlawson/ember-pouch/issues/81

### CODE REVIEW

**Comment by rsutphin** [comment]
The tests are mostly failing because of the changes that remove backwards compatibility with older ember-datas. The 1.13 tests are failing because the asynchronous reload introduced in the case where the record is still loading when the change occurs assumes that the record will be loaded in the next tick. That's not guaranteed.

I don't think any of this is necessary. Checking if the rev is different is simply a matter of adding another condition to this `if`: https://github.com/nolanlawson/ember-pouch/blob/master/addon/adapters/pouch.js#L55

**Comment by broerse** [comment]
I don know how to do the `if` without adding asynchronicity. https://github.com/nolanlawson/ember-pouch/blob/master/addon/adapters/pouch.js#L51 is true the next ember run if you make the change. It is false if the change was made remote. The same it true for https://github.com/nolanlawson/ember-pouch/blob/master/addon/adapters/pouch.js#L55. The rev in Ember Data is updated the next ember run if you make the change.

If it is simply a matter of adding another condition to this `if` how is it done?

https://github.com/nolanlawson/ember-pouch/issues/50 is the issue that needs to be solved. I believe this solves it.

**Comment by rsutphin** [comment]
(I changed the URLs to match the line numbers when you made your comment @broerse — the lines have shifted since I merged #83.)

> https://github.com/nolanlawson/ember-pouch/blob/c15b0850d52512fde3ed5860e071f50da9c6d4db/addon/adapters/pouch.js#L51 is true the next ember run if you make the change. It is false if the change was made remote.

It's also true immediately if you made the change. In either case it may or may not be true if the change was remote — it depends on if the record was loaded locally before the change occurred.

In any case, it seems like we had different understandings of what #81 was about. I've investigated and the thing I thought that #81 would address is actually moot (I put a comment on that ticket explaining). You were thinking it was about automatically loading new records, which I think we agree now should be discussed further on #50. Okay to close this?

**Comment by broerse** [comment]
Okay to close it.

**Pull request closed without merging**
