### PR TITLE
This pull request fixes an serializer issue with Ember-Data 1.0.0-beta.15

### PR DESCRIPTION
**Pull request by OleRoel**
See [issue #45](https://github.com/nolanlawson/ember-pouch/issues/45)

Not ready for merge, since this hasn't been tested with older versions of Ember-Data.

### CODE REVIEW

**Comment by nolanlawson** [comment]
Can someone please test with an older version of Ember Data? Then I'm :+1: to merge.

**Comment by nolanlawson** [comment]
Seems like we'll need to check for `_createSnapshot`, in order to support older versions of Ember-Data.

**Comment by OleRoel** [comment]
No, it doesn't work with older versions. The snapshot API just arrived in beta.15. With beta.14 you get a 'record._createSnapshot is not a function'. Now, what is the best way to handle API changes? Test for the existence of '_createSnapshot'?

**Comment by nolanlawson** [comment]
Yup, that's exactly what I propose. :)  See #47.

**Comment by nolanlawson** [comment]
Ah shoot, you also only modified the `dist` files. Hang on, I'll fix it in #47.

**Comment by OleRoel** [comment]
Ok, I am happy if you make the code changes, my six year old son is demanding some time from me.

**Comment by nolanlawson** [comment]
fixed by https://github.com/nolanlawson/ember-pouch/pull/47

**Pull request closed without merging**
