### PR TITLE
Pragmatic fix for Snapshot issue with Ember Data version 1.0.0-beta.14, 15 and 16

### PR DESCRIPTION
**Pull request by OleRoel**
See issue #48 

This fix hasn't been tested yet.

### CODE REVIEW

**Comment by OleRoel** [comment]
This works for Ember Data 1.0.0-beta.16.1

**Comment by nolanlawson** [comment]
Can someone else confirm that this works in beta.16 as well as maybe 14 or 15? Unfortunately I don't have the time for this, and I made a huge mistake by not automating the test process, especially given how fast Ember Data seems to be changing... :confused:

**Comment by OleRoel** [comment]
I'll test the version 14-16 tomorrow, but also would be happy if someone else likes to jump in.

**Comment by OleRoel** [comment]
Tested the code change with Ember Data versions 1.0.0-beta.14, 15, 16, 16.1. My tests were simply creating, reading, changing and deleting a record (also known as CRUD). Everything worked fine and as expected in the different versions with the change in the PR. No messages from Ember Data were logged into the console.

**Comment by nolanlawson** [comment]
Until we get real automated tests, that's good enough for me. :) Publishing now.

**Comment by nolanlawson** [comment]
Squashed and merged as fdb1d042f61d577ffe8a10d32fd815367c2716df

**Comment by nolanlawson** [comment]
published in 1.2.5

**Pull request closed without merging**
