### PR TITLE
Update Bower dependencies

### PR DESCRIPTION
**Pull request by broerse**

### CODE REVIEW

**Comment by broerse** [comment]
We need a more up-to-date pouch version to fix the Chrome Update 52 bug. https://github.com/nolanlawson/pouchdb-authentication/pull/115

**Comment by aexmachina** [comment]
@nolanlawson you happy for me to merge this and push new versions?

**Comment by broerse** [comment]
@nolanlawson I can merge this and release new minor version but you will have to push it to NPM.

**Comment by nolanlawson** [comment]
LGTM!

**Comment by nolanlawson** [comment]
@broerse you are now both a collaborator and an npm owner, please don't feel blocked again by my awful backlog of OSS tickets, cheers!

**Comment by broerse** [comment]
@nolanlawson Thanks!

**Comment by broerse** [comment]
@nolanlawson my NPM name is martinic please make that the owner

**Pull request merged**
